name: Build project

on:
  pull_request: {}
  push: { branches: [main] }
  release: { types: [published] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  
jobs:
#empty commit
  # testAllModes:
  #   name: Test project with Unity ${{ matrix.unityVersion }} in ${{ matrix.testMode }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       unityVersion:
  #         - 2020.2.3f1      
  #       testMode:
  #         - playmode
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         lfs: true
  #     - name: Cache Library
  #       uses: actions/cache@v2
  #       with:
  #         path: Library
  #         key: Library
  #     - id: tests
  #       name: Run tests in Unity        
  #       uses: game-ci/unity-test-runner@v2.0-alpha-2
  #       with:
  #         customImage: 'serjame/unity-editor-opencv:2020.2.3f1'
  #         unityVersion: ${{ matrix.unityVersion }}             
  #         testMode: ${{ matrix.testMode }}
  #         artifactsPath: ${{ matrix.testMode }}-artifacts
  #     - uses: actions/upload-artifact@v1
  #       with:
  #         name: Test results for ${{ matrix.testMode }}
  #         path: ${{ steps.tests.outputs.artifactsPath }}
  #
  printjobAction:
    name: jobaction
    runs-on: ubuntu-latest
    steps:
      - run: echo job = ${{github.job}}, github.event_name = ${{github.event_name}}, id = ${{github.event.id}}, payload = ${{github.event.payload}}      

  pushJob:
    name: This jub will run on push
    runs-on: ubuntu-latest    
    if: github.event_name == 'push'
    steps:
    - name: dummy job
      run: echo this is job - ${{github.job}}

  pullRequestJob:
    name: This jub will run on pull_request
    runs-on: ubuntu-latest    
    if: github.event_name == 'pull_request'
    steps:
    - name: dummy job
      run: echo this is job - ${{github.job}}

  printSelectedGroupJob:
    runs-on: ubuntu-latest            
    steps:
      - name: set dev groups
        if: github.event_name == 'push'        
        uses: allenevans/set-env@v2.0.0
        with:
          FIREBASE_TESTERS_GROUP: 'devs'
      - name: set product groups
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: allenevans/set-env@v2.0.0
        with:
          FIREBASE_TESTERS_GROUP: 'productTeam'

      - run: echo "product team setted to ${FIREBASE_TESTERS_GROUP}"

  generateChangeLog:
    name: Generate change log
    runs-on: ubuntu-latest    
    steps:        
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          lfs: false      
      - name: Generate changelog from git
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #sinceTag: ${{needs.getBuildVersion.outputs.buildVersion}}
          user: spaskhalov
          project: test-unity-ci          
          stripHeaders: false
          stripGeneratorNotice: true
          author: true
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          verbose: true
          compareLink: true
          httpCache: true
          filterByMilestone: true
          unreleased: true          
      - name: Upload changelog
        uses: actions/upload-artifact@v1
        with:
          name: Changelog
          path: CHANGELOG.md
  
  releaseJob:
    name: This jub will run on release (published)
    runs-on: ubuntu-latest    
    needs: generateChangeLog
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: dummy job
        run: echo this is job - ${{github.job}}    
      - name: print curent dir
        run: |        
          pwd        
          ls 
      - name: print upper dir
        run: |
          cd ..        
          pwd        
          ls
      - name: Update Release Body
        uses: tubone24/update_release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md