name: Build project

on:
  pull_request: {}
  push: { branches: [main] }
  release: { types: [published] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  
jobs:
  # testAllModes:
  #   name: Test project with Unity ${{ matrix.unityVersion }} in ${{ matrix.testMode }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       unityVersion:
  #         - 2020.2.3f1      
  #       testMode:
  #         - playmode
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         lfs: true
  #     - name: Cache Library
  #       uses: actions/cache@v2
  #       with:
  #         path: Library
  #         key: Library
  #     - id: tests
  #       name: Run tests in Unity        
  #       uses: game-ci/unity-test-runner@v2.0-alpha-2
  #       with:
  #         customImage: 'serjame/unity-editor-opencv:2020.2.3f1'
  #         unityVersion: ${{ matrix.unityVersion }}             
  #         testMode: ${{ matrix.testMode }}
  #         artifactsPath: ${{ matrix.testMode }}-artifacts
  #     - uses: actions/upload-artifact@v1
  #       with:
  #         name: Test results for ${{ matrix.testMode }}
  #         path: ${{ steps.tests.outputs.artifactsPath }}
  #
  printjobAction:
    name: jobaction
    runs-on: ubuntu-latest
    steps:
      - run: echo job = ${{github.job}}, github.event_name = ${{github.event_name}}, id = ${{github.event.id}}, payload = ${{github.event.payload}}      

  pushJob:
    name: This jub will run on push
    runs-on: ubuntu-latest    
    if: github.event_name == 'push'
    steps:
    - name: dummy job
      run: echo this is job - ${{github.job}}
  
  releaseJob:
    name: This jub will run on release (published)
    runs-on: ubuntu-latest    
    if: github.event.action == 'published'
    steps:
    - name: dummy job
      run: echo this is job - ${{github.job}}
  
  pullRequestJob:
    name: This jub will run on pull_request
    runs-on: ubuntu-latest    
    if: github.event.action == 'pull_request'
    steps:
    - name: dummy job
      run: echo this is job - ${{github.job}}
