name: Build project

on:
  pull_request: {}
  push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  
jobs:
  testAllModes:
    name: Test project with Unity ${{ matrix.unityVersion }} in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        unityVersion:
          - 2020.1.17f1      
        testMode:
          - playmode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library
      - name: Run tests in Unity
        uses: game-ci/unity-test-runner@v2.0-alpha-2
        with:
          unityVersion: ${{ matrix.unityVersion }}             
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}